CURRENCY = {
	"Orb of Alteration": "alt",
	"Orb of Fusing": "fuse",
	"Orb of Alchemy": "alch",
	"Chaos Orb": "chaos",
	"Gemcutter's Prism": "gcp",
	"Exalted Orb": "exa",
	"Chromatic Orb": "chrom",
	"Jeweller's Orb": "jew",
	"Engineer's Orb": "engineers-orb",
	"Orb of Chance": "chance",
	"Cartographer's Chisel": "chisel",
	"Orb of Scouring": "scour",
	"Blessed Orb": "blessed",
	"Orb of Regret": "regret",
	"Regal Orb": "regal",
	"Divine Orb": "divine",
	"Vaal Orb": "vaal",
	"Orb of Annulment": "orb-of-annulment",
	"Orb of Binding": "orb-of-binding",
	"Ancient Orb": "anient-orb",
	"Orb of Horizons": "orb-of-horizons",
	"Harbinger's Orb": "harbingers-orb",
	"Scroll of Wisdom": "wis",
	"Portal Scroll": "port",
	"Armourer's Scrap": "scr",
	"Blacksmith's Whetstone": "whe",
	"Glassblower's Bauble": "ba",
	"Orb of Transmutation": "tra",
	"Orb of Augmentation": "aug",
	"Mirror of Kalandra": "mir",
	"Eternal Orb": "ete",
	"Perandus Coin": "p",
	"Silver Coin": "silver",
	"Annulment Shard": "annulment-shard",
	"Mirror Shard": "mirror-shard",
	"Exalted Shard": "exalted-shard",
	"Binding Shard": "binding-shard",
	"Horizon Shard": "horizon-shard",
	"Harbinger's Shard": "harbinger's-shard",
	"Engineer's Shard": "engineers-shard",
	"Ancient Shard": "ancient-shard",
	"Chaos Shard": "chaos-shard",
	"Regal Shard": "regal-shard",
	"Simple Sextant": "apprentice-sextant",
	"Prime Sextant": "journeyman-sextant",
	"Awakened Sextant": "master-sextant",
	"Blessing of Xoph": "blessing-xoph",
	"Blessing of Tul": "blessing-tul",
	"Blessing of Esh": "blessing-esh",
	"Blessing of Uul-Netol": "blessing-uul-netol",
	"Blessing of Chayula": "blessing-chayula",
	"Splinter of Xoph": "splinter-xoph",
	"Splinter of Tul": "splinter-tul",
	"Splinter of Esh": "splinter-esh",
	"Splinter of Uul-Netol": "splinter-uul",
	"Splinter of Chayula": "splinter-chayula",
	"Timeless Karui Splinter": "timeless-karui-splinter",
	"Timeless Maraketh Splinter": "timeless-maraketh-splinter",
	"Timeless Eternal Empire Splinter": "timeless-eternal-empire-splinter",
	"Timeless Templar Splinter": "timeless-templar-splinter",
	"Timeless Vaal Splinter": "timeless-vaal-splinter",
	"Stacked Deck": "stacked-deck"
}

CURRENCY_REV = {v: k for k, v in CURRENCY.items()}