[tool.poetry]
name = "Path-of-Accounting"
version = "0.1.0"
description = ""
authors = ["Ethck"]

[tool.poetry.dependencies]
python = "^3.7"
typing = "^3.7.4"
requests = "^2.22.0"
colorama = "^0.4.3"
keyboard = "^0.13.4"

[tool.poetry.dev-dependencies]
pytest = "^3.4"
