# Uses hotkeys, turn to False to not use hotkeys
use_hotkeys: True

# User's league
# Current leagues:
# Standard
# Hardcore
# Metamorph
# Hardcore Metamorph
league: Metamorph

# Whether or not to use the GUI
use_gui: True